[package]
name = "rusmpp"
version = "0.4.0"
edition = "2024"
rust-version = "1.85.0"
description = "A Rust SMPP library."
authors = ["Jad K. Haddad <jadkhaddad@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rusmpp/Rusmpp"
readme = "../Readme.md"
keywords = ["smpp", "smsc", "messaging", "networking", "protocol"]

[dependencies]
rusmpp-core = { path = "../rusmpp-core", version = "0.4.0", default-features = false, features = [
    "alloc",
] }
rusmpp-tokio-codec = { path = "../rusmpp-tokio-codec", version = "0.1.0", default-features = false, optional = true }
rusmpp-extra = { path = "../rusmpp-extra", version = "0.4.0", default-features = false, features = [
    "alloc",
] }

[dev-dependencies]
tracing = { version = "0.1.43" }
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = { version = "0.7.17", default-features = false, features = [
    "codec",
] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
futures = "0.3.31"


[features]
default = ["tokio-codec"]
# Implements tokio's util codec Encoder/Decoder traits.
tokio-codec = ["dep:rusmpp-tokio-codec"]
# Enables encoding/decoding and concatenation support for SubmitSm.
extra = ["rusmpp-extra/encoding", "rusmpp-extra/concatenation"]
# Derives serde Serialize and Deserialize for all SMPP types.
serde = ["rusmpp-core/serde"]
# Enables logging via the `tracing` crate.
tracing = ["rusmpp-tokio-codec/tracing"]

[[example]]
name = "client_server"
path = "examples/client_server.rs"
required-features = ["tokio-codec", "tracing"]

[[example]]
name = "simple"
path = "examples/simple.rs"
required-features = ["tokio-codec"]

[[example]]
name = "submit_sm"
path = "examples/submit_sm.rs"
required-features = ["tokio-codec", "tracing"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
